PREFIX darq: <http://darq.sf.net/dose/0.1#>
PREFIX ext: <http://sadiframework.org/ontologies/DARQ/darq-extensions.owl#>

SELECT DISTINCT ?predicate 
WHERE {

	[] a darq:Service; 
	   darq:url %u%; 
	   ext:graph ?graph .
	   
	?graph darq:capability ?capability .
	?capability darq:predicate ?predicate .

}
