PREFIX sadi: <http://sadiframework.org/ontologies/properties.owl#>
PREFIX ss: <http://semanticscience.org/resource/>
PREFIX go: <http://lsrn.org/GO:>

SELECT ?protein ?omim
WHERE {
     ?protein sadi:hasFunction go:0004872 .  # "receptor activity"
     ?protein sadi:isParticipantIn go:0007595 . # "lactation"
     ?protein sadi:isCausallyRelatedWith ?omim . 
}

