PREFIX uniprot: <http://bio2rdf.org/uniprot:>
PREFIX core: <http://purl.uniprot.org/core/>
PREFIX core2: <http://bio2rdf.org/core:>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?substitution ?start ?end ?dbCrossRef
WHERE {
   
    uniprot:P01344 core:annotation ?annotation .
    ?annotation rdf:type core2:Natural_Variant_Annotation .
   
    ?annotation rdfs:seeAlso ?dbCrossRef .
    ?annotation core:substitution ?substitution .
   
    ?annotation core:range ?range .
    ?range core:begin ?start .
    ?range core:end ?end .

}

