PREFIX drug: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/>
PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX core: <http://purl.uniprot.org/core/>
PREFIX omim: <http://bio2rdf.org/mim:>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT ?targetProtein ?alzProtein ?alzProteinName
WHERE {
   
    drug:DB01273 drugbank:target ?target .
    ?target drugbank:swissprotId ?targetProtein .

    ?alzProtein rdfs:seeAlso omim:104300 .
    ?alzProtein dc:title ?alzProteinName .

    ?targetProtein core:interaction ?interaction .
    ?interaction core:participant ?participant .
    ?participant owl:sameAs ?alzProtein .

}
