PREFIX probeset: <http://bio2rdf.org/affymetrix:>
PREFIX core: <http://purl.uniprot.org/core/>
PREFIX core2: <http://bio2rdf.org/core:>
PREFIX affy: <http://bio2rdf.org/ns/affymetrix#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?geneID ?proteinID ?substitution ?start ?end ?dbCrossRef ?paperTitle
WHERE {
   
    # gene IDs

    probeset:53701_at affy:xEnsembl ?geneID .

    # protein IDs

    probeset:53701_at affy:xSwissProt ?proteinID .

    # GO terms

#    probeset:53701_at affy:xGene_Ontology_Biological_Process ?goProcess .
#    probeset:53701_at affy:xGene_Ontology_Cellular_Component ?goComponent .
#    probeset:53701_at affy:xGene_Ontology_Molecular_Function ?goFunction .
 
    # SNPs
   
    ?proteinID core:annotation ?annotation .
    ?annotation rdf:type core2:Natural_Variant_Annotation .
    ?annotation rdfs:seeAlso ?dbCrossRef .

    ?annotation core:range ?range .
    ?range core:begin ?start .
    ?range core:end ?end .
       
    # literature

#    ?proteinID core:citation ?paper .
#    ?paper core:title ?paperTitle .  
    
}
