PREFIX drug: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/>
PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>
PREFIX diseasome: <http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/>
PREFIX bio2rdf: <http://bio2rdf.org/ns/bio2rdf#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?targetProtein ?gene ?disease ?diseaseName
WHERE {
    drug:DB00421 drugbank:target ?targetProtein .
    ?targetProtein drugbank:hgncId ?gene .
    ?gene bio2rdf:xOMIM ?omim .
    ?disease diseasome:omim ?omim .
    ?disease rdfs:label ?diseaseName . 
}
