PREFIX svc: <http://www.mygrid.org.uk/mygrid-moby-service#>
PREFIX dc: <http://protege.stanford.edu/plugins/owl/dc/protege-dc.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX moby: <http://moby/>

SELECT DISTINCT ?service
FROM <http://mobyreg/services/>
WHERE
{
   ?service svc:hasOperation ?operation . 
   
   ?operation svc:inputParameter ?input .
   ?operation svc:outputParameter ?output .
   
   ?input svc:hasParameterNameText ?inputname .
   ?output svc:hasParameterNameText ?outputname .
   
   ?input ?predicate ?output .
}