PREFIX rdfs: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX svc: <http://www.mygrid.org.uk/mygrid-moby-service#>
PREFIX ns: <http://biomoby.org/RESOURCES/MOBY-S/Namespaces/>
SELECT DISTINCT ?predicate
FROM <http://mobyreg/services/>
WHERE
{
    ?service svc:hasOperation ?operation .
    ?operation svc:inputParameter ?input .
    ?operation svc:outputParameter ?output .
    ?input ?predicate ?output .
    ?input svc:inNamespaces ?input_namespaces_node .
    ?input_namespaces_node rdfs:type svc:parameterNamespace .
    ?input_namespaces_node rdfs:type ns:%v%
}