# Test case where predicate variable has bindings, but non that
# are URIs.

PREFIX pred: <http://sadiframework.org/ontologies/predicates.owl#>
PREFIX uniprot: <http://lsrn.org/UniProt:>

SELECT *
WHERE {
   uniprot:P04036 pred:hasSequence ?sequence .
   uniprot:P04036 ?sequence ?o .
}