PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sadi: <http://sadiframework.org/ontologies/sadi.owl#>

SELECT DISTINCT ?p
WHERE
{
	%u% rdf:type sadi:Service .
	%u% sadi:providesPredicate ?p
}