PREFIX svc: <http://www.mygrid.org.uk/mygrid-moby-service#>
PREFIX dc: <http://protege.stanford.edu/plugins/owl/dc/protege-dc.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX moby: <http://moby/>
PREFIX mobyobj: <http://biomoby.org/RESOURCES/MOBY-S/Objects/>
PREFIX namespace: <http://biomoby.org/RESOURCES/MOBY-S/Namespaces/>

SELECT *
FROM <http://mobyreg/services/>
WHERE
{
	?service svc:hasOperation ?operation .
	?operation svc:inputParameter ?input .
	?operation svc:outputParameter ?output .
	
	#----------------------------------------------------------------------
	# A variable number of triples is inserted
	# here, for matching triples that connect
	# ?input and ?output by the desired predicate
	# URI (or any of its synonyms).
	#----------------------------------------------------------------------
	
	%v%
	
	
	?input svc:objectType ?input_objtype_node .
	?input_objtype_node rdf:type %u% .

	?input svc:inNamespaces ?input_namespaces_node .
	
	#-----------------------------------------------------------------------
 	# A variable number of patterns for matching
 	# input namespaces is inserted here.
 	#----------------------------------------------------------------------- 
 	
	%v%		
	
	?output svc:objectType ?output_objtype_node .
	?output rdf:type %u% .
	
	?output svc:inNamespaces ?output_namespaces_node .
	
	#-----------------------------------------------------------------------
 	# A variable number of patterns for matching
 	# output namespaces is inserted here.
 	#----------------------------------------------------------------------- 

	%v%
}