PREFIX svc: <http://www.mygrid.org.uk/mygrid-moby-service#>

SELECT DISTINCT ?pred
FROM <http://mobyreg/services/>
WHERE
{
	?service svc:hasOperation ?operation .
	
    ?operation svc:inputParameter ?inputarg . 
    ?operation svc:outputParameter ?outputarg .
    
	?inputarg ?pred ?outputarg .
    
}