#!/usr/bin/perl -w
use strict;
use DBI;
use DBD::mysql;
use SADI::Service::Core;
use lib ".";
use SOAP::Lite;
use HTTP::Cookies;


#http://soap.bind.ca/help_soap_api.jsp
## Get a BINDSOAP Service proxy as described by the WSDL file.
## The proxy will handle the cookie-based sessions.
#my $service = SOAP::Lite
#	-> service('http://soap.bind.ca/bind.wsdl')
#	-> proxy('http://soap.bind.ca/services/BINDSOAP',
#		cookie_jar => HTTP::Cookies->new(ignore_discard => 1));
#
#
#print "idSearch()\n";
#my $resultBean = $service->idSearch("11621","bindid","flat");
#print "\t" . $resultBean->{'totalRecordsFound'} . " records(s) found.\n";

my $service = SADI::Service::Core->new(
    ServiceName => "getMolecularInteractions",
    ServiceType => "http://sadiframework.org/RESOURCES/___NoIdea___",
    InputClass => "http://purl.oclc.org/SADI/LSRN/UniProt_Record",
    OutputClass => "http://sadiframework.org/ontologies/service_objects.owl#getMolecularInteractions_Output",
    Description => "gets the BIND interaction ids for a given UniProt protein",
    UniqueIdentifier => "urn:lsid:sadiframework.org:serviceinstances:sadiframework.net,getMolecularInteractions",
    Authority => "illuminae.com",
    ServiceURI => "http://sadiframework.org/services/getMolecularInteractions",
    URL => "http://sadiframework.org/services/getMolecularInteractions",
    #_default_request_method => "POST",
                                    
    );

$service->sendInterfaceOnGET ;  # if GET then send interface and exit
$service->Prepare() || die "somehow the input data was improperly formed\n";

my @inputs = $service->getInputNodes();

my %values;
foreach (@inputs){
	my $URI = $_->getURI;
	$URI =~ /[#\/](\S+)$/;  # get the id numbers
	next unless $1;
	$values{$URI} = $1;
}

&process_data($service,\%values);

$service->Respond();


sub process_data {
    my ($service, $values) = @_;
    
    my %values = %$values;
    my $acc_string;
    foreach my $accession(values %values){
    	$acc_string .= "\"GO:$accession\",";
    }
    chop $acc_string;  # remove trailing comma 
    print STDERR "select acc, name, term_definition from term, term_definition where term.id = term_definition.term_id and acc IN ($acc_string)";
    my $sth = $dbh->prepare("select acc, name, term_definition from term, term_definition where term.id = term_definition.term_id and acc IN ($acc_string)");
    $sth->execute;
    while (my ($acc, $name, $def) = $sth->fetchrow_array()){
		my $id = ($acc =~ /GO:(\d+)/ && $1);  # need to strip-off the GO: prefixs]
	    foreach my $node(keys %values){
	   		if ($node =~ /$id/){
	            	$service->addOutputData(node => $node,
	                                        value => $name,
	                                        predicate => "http://es-01.chibi.ubc.ca/~benv/predicates.owl#hasTermName"
	                                    );
	                $service->addOutputData(node => $node,
	                                        value => $def,
	                                        predicate => "http://es-01.chibi.ubc.ca/~benv/predicates.owl#hasTermDefinition"
	                                    );
	                last;                                    
	   		}    
	    }
	}
}


sub _dbAccess {


        my ($dsn) = "DBI:mysql:go_latest:mysql.ebi.ac.uk:4085";
        my $dbh = DBI->connect($dsn, 'go_select', 'amigo', {RaiseError => 1}) or die "can't connect to database";

        return ($dbh);
}

