PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sadi: <http://sadiframework.org/ontologies/sadi.owl#>
PREFIX mygrid: <http://www.mygrid.org.uk/mygrid-moby-service#>

SELECT *
WHERE
{
	%u% rdf:type sadi:Service .
	OPTIONAL {
		%u% sadi:serviceStatus ?statusNode .
		?statusNode dc:date ?date .
		?statusNode rdfs:value ?status .
	}
}
ORDER BY DESC(?date)