#!/usr/bin/perl -w
# This is a CGI-BIN script, invoked by a web server when an HTTP
# POST comes in, dispatching requests to the appropriate module
# (SADI web service).
#
# It includes some hard-coded paths - they were added during the
# generate service call.
#
# $Id: service-cgi-async.tt,v 1.19 2009-12-01 19:44:31 ubuntu Exp $
# Contact: Edward Kawas <edward.kawas@gmail.com>
# ---------------------------------------------------------------

#-----------------------------------------------------------------
# Authority:    dev.biordf.net
# Service name: getUniprotByKeggGene
# Generated:    19-Jan-2010 16:06:09 PST
# Contact: Edward Kawas <edward.kawas@gmail.com>
#-----------------------------------------------------------------

use strict;


# --- during service generation --- 
# leave at the top!
use lib '/home/kawas/Perl-SADI/generated';
use lib '/home/kawas/Perl-SADI/services';
use lib '/home/kawas/Perl-SADI';

use CGI;
use CGI::Carp qw(fatalsToBrowser);

use SADI::Service::Instance;
use SADI::RDF::Core;
use SADI::Generators::GenServices;
use SADI::FileStore;

# limit the max size of a post - change it as you see fit
$CGI::POST_MAX=1024 * 1024 * 10;  # max 10MB posts

# the suggested wait time for polling in milliseconds
my $SUGGESTED_WAIT_TIME = 15*1000;

# here we require the service module and add it to ISA hierarchy
use base 'Service::getUniprotByKeggGene';

# if this is a GET, send the service interface
if ($ENV{REQUEST_METHOD} eq 'GET' or $ENV{REQUEST_METHOD} eq 'HEAD') {
    my $q = new CGI;
    # print the interface unless we are polling
    do {
        # send the signature for this service
        # instantiate a new SADI::RDF::Core object
        my $core = SADI::RDF::Core->new;
        # set the Instance for $core
        $core->Signature(__PACKAGE__->get_service_signature('getUniprotByKeggGene'));
        print $q->header(-type=>'application/rdf+xml');
        print $core->getServiceInterface();
        exit();
    } unless $q->param('poll');
    
    # we are polling ... 
    # $poll is the id for our file store
    my $poll = $q->param('poll');
    $ENV{SADI_UID} = $poll;
    my $completed;
    eval {$completed = __PACKAGE__->completed($poll);};
    # do something if $@
    print $q->header(-status=>"404 nothing found for the given polling parameter" ) if $@;
    exit if $@;
    if ($completed) {
        # we are done
        eval {$completed = __PACKAGE__->retrieve($poll);};
        unless ($@) {
          print $q->header(-type=>'application/rdf+xml');
          print $completed;
          exit;
        }
    } else {
        # still waiting
        my $signature = __PACKAGE__->get_service_signature('getUniprotByKeggGene');
        print $q->redirect(-uri=>$signature->URL . "?poll=$poll", -status=>302, -pragma=>"sadi-please-wait = $SUGGESTED_WAIT_TIME");
        #print $q->header(-type=>'application/rdf+xml', -sadi_please_wait=>$SUGGESTED_WAIT_TIME);
        #print __PACKAGE__->get_polling_rdf();
        exit;
    }
} else {
    # call the service

    # get the data from the 'data' parameter or from POSTDATA
    my $data = join "",<>;

    # set the UID
    my $uid = SADI::FileStore->new(ServiceName => "getUniprotByKeggGene")->generate_uid();
    $ENV{SADI_UID} = $uid;

    # call the service
    __PACKAGE__->getUniprotByKeggGene(
       $data
    );
   my $q = new CGI;
   print $q->header(
     -type=>'application/rdf+xml',
     -status=>202, 
     -pragma=>"sadi-please-wait = $SUGGESTED_WAIT_TIME"
   );
   print __PACKAGE__->get_polling_rdf();
}

__END__