PREFIX svc: <http://www.mygrid.org.uk/mygrid-moby-service#>
PREFIX dc: <http://protege.stanford.edu/plugins/owl/dc/protege-dc.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX moby: <http://moby/>

SELECT *
FROM <http://mobyreg/services/> 
{

   %u% svc:hasServiceNameText ?name .
   %u% svc:hasServiceDescriptionText ?desc .
   %u% svc:locationURI ?url .
   %u% dc:identifier ?lsid .
   
   %u% svc:providedBy ?provider_node .
   ?provider_node dc:publisher ?authority .
   ?provider_node dc:creator ?email .
   ?provider_node svc:authoritative ?authoritative .

   %u% svc:hasOperation ?operation .
   ?operation svc:performsTask ?task_node .
   ?task_node rdf:type ?servicetype .
   
   # Want the Moby service type, not the myGrid service type.
   FILTER regex(?servicetype, "MOBY-S")
	   
   # Location of an RDF file describing the service.
   %u% svc:hasServiceDescriptionLocation ?rdfurl .    
   
   # Can the service be called asynchronously?
   # If yes, format will be "moby-async".  
   # Otherwise, just "moby".

   %u% dc:format ?format .

}
