PREFIX darq: <http://darq.sf.net/dose/0.1#>
PREFIX darqx: <http://sadiframework.org/ontologies/DARQ/darq-extensions.owl#>
PREFIX sadi: <http://sadiframework.org/ontologies/sadi.owl#>

SELECT ?url 
WHERE {

	[] a darq:Service;
	   sadi:serviceStatus ?status;
	   darq:url ?url .

	FILTER (!sameTerm(?status, sadi:dead))

}
