package ca.wilkinsonlab.daggoo;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class SAWSDLService {

    /**
     * The default name of the loweringSchemaMapping file generated by SAWSDL generator
     */
    public static final String LOWERING_FILENAME = "lowering.xml";
    /**
     * The default name of the liftingSchemaMapping file generated by SAWSDL generator
     */
    public static final String LIFTING_FILENAME = "lifting.xml";
    /**
     * The default name of the owl file, containing our service input and output classes, generated by SAWSDL generator
     */
    public static final String OWL_FILENAME = "service.owl";
    
    /**
     * The default endpoint to register our SADI services 
     */
    public static final String REGISTRY_ENDPOINT = "http://sadiframework.org/registry/register";
    
    private String name = "";

    private String wsdlLocation = "";
    
    private String loweringSchemaLocation = "";
    
    private String liftingSchemaLocation = "";
    
    private String owlClassLocation = "";

    private HttpServletRequest request;

    private HttpServletResponse response;

    public SAWSDLService() {

    }

    public String getName() {
	return name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public String getWsdlLocation() {
	return wsdlLocation;
    }

    public void setWsdlLocation(String wsdlLocation) {
	this.wsdlLocation = wsdlLocation;
    }

    @Override
    public String toString() {
	return String.format("%s(%s)", getName(), getWsdlLocation());
    }

    /**
     * Returns the HttpServletRequest associated with this service. This is
     * notably useful to access the request URI, for example to generate the
     * polling URLs for asynchronous service requests.
     * 
     * @return the HttpServletRequest
     */
    public HttpServletRequest getRequest() {
	return request;
    }

    public void setRequest(HttpServletRequest request) {
	this.request = request;
    }

    /**
     * Returns the HttpServletResponse associated with this service. This
     * is notably useful to access the output stream directly, though you should
     * be careful in doing so because many of the other methods of
     * ServiceServlet will be assuming it's empty and uncommitted.
     * 
     * @return the HttpServletResponse
     */
    public HttpServletResponse getResponse() {
	return response;
    }

    public void setResponse(HttpServletResponse response) {
	this.response = response;
    }

    public String getLoweringSchemaLocation() {
        return loweringSchemaLocation;
    }

    public void setLoweringSchemaLocation(String loweringSchemaLocation) {
        this.loweringSchemaLocation = loweringSchemaLocation == null ? "" : loweringSchemaLocation.trim();
    }

    public String getLiftingSchemaLocation() {
        return liftingSchemaLocation;
    }

    public void setLiftingSchemaLocation(String liftingSchemaLocation) {
        this.liftingSchemaLocation = liftingSchemaLocation == null ? "" : liftingSchemaLocation.trim();
    }

    public String getOwlClassLocation() {
        return owlClassLocation;
    }

    public void setOwlClassLocation(String owlClassLocation) {
        this.owlClassLocation = owlClassLocation == null ? "" : owlClassLocation.trim();
    }
    
    

}
